# Site settings
title: Kotlin Nights La Paz
description: Transmisiones y material de los Kotlin Nights de la comunidad Kotlin La Paz.
keywords: Kotlin, Kotlin Nights, Android
author: lizarragadev
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://nights.kotlinlapaz.dev" # the base hostname & protocol for your site
comments: true