# Site settings
title: Kotlin Nights La Paz
description: El lenguaje de programación número 1 para el desarrollo de aplicaciones Android.
keywords: Kotlin, Kotlin Nights, Android
author: lizarragadev
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://nights.kotlinlapaz.dev" # the base hostname & protocol for your site
comments: true